### ISSUE TITLE
Option to annotate

### ISSUE THREAD

**Issue by GuruTeja-Tebs** [explosion/spacy-streamlit#13]
Hi, 
Is there an option to input text and annotate content?
Like a text annotation tool, can this be used?

**Comment by honnibal** [comment]
You can check out our annotation tool Prodigy here: https://prodi.gy . Prodigy is our commercial product, it funds development of spaCy.

**Comment by GuruTeja-Tebs** [comment]
Prodigy suits the requirement well but its a paid one, Am looking for an free / open source alternative with minimum required features.
