### ISSUE TITLE
Be able to specify port & host

### ISSUE THREAD

**Issue by koaning** [explosion/spacy-streamlit#16]
I'm currently running the spacy-streamlit app on a server. I prefer to have this on my server on my local network because otherwise my laptop gets *very* hot during training. In order to properly host it though I need to be able to customise the port-number as well as the host. It seems like these settings are currently missing. Would @ines you be open to these commands? I wouldn't mind picking this up.

**Comment by polm** [comment]
Sorry for the late reply - it'd be great to have a PR for this.

**Comment by koaning** [comment]
Cool. I may have a go at this later this week then 😃 !

**Comment by koaning** [comment]
I'm not sure if this wasn't a feature back in March, but it seems that you don't need to configure `spacy-streamlit` for this because streamlit basically does this out of the box. 

```
python -m streamlit run app.py --server.port 12345 --server.address 0.0.0.0
```

Sooo, no need for a PR. 😅

**Comment by polm** [comment]
Ah, I wondered about that - I thought you wanted to specify it in code or something. Thanks for checking in any case!
