### ISSUE TITLE
spaCy 3.1 Support

### ISSUE THREAD

**Issue by kinghuang** [explosion/spacy-streamlit#19]
The `spacy-streamlit` module currently requires `spacy>=3.0.0,<3.1.0`, making it unusable with spaCy 3.1. As far as I can tell, it shouldn't break with 3.1. Can this requirement be updated to allow 3.1?

https://github.com/explosion/spacy-streamlit/blob/d828e1dce6661250ae153e235b7a24289e2f30b8/setup.cfg#L16

**Comment by adrianeboyd** [comment]
Sure, that was just an oversight...
