### ISSUE TITLE
Support for span categorizer?

### ISSUE THREAD

**Issue by jonmcalder** [explosion/spacy-streamlit#23]
Is it possible to visualize spancat predictions via `spacy-streamlit` yet? Either directly or by customizing one of the existing visualizers? I haven't been able to find any examples of this.

**Comment by polm** [comment]
I don't think so. Spancat introduces some hard cases, like crossing annotations or arbitrarily nested spans, that would need a different visualization strategy than NER.

If you have non-overlapping spans or some way to select a non-overlapping subset, you could copy them to `doc.ents` and use the NER visualization.

**Comment by jonmcalder** [comment]
Ok thanks. Should this issue remain open for a while in case a solution for this is considered going forward or should it be closed?

**Comment by polm** [comment]
Yes, it's fine to leave it open as a potential enhancement.

**Comment by shaked571** [comment]
I guess you close it now... I saw you also added an example. I actually just implemented myself yesterday as well and I see you just added an example for spans yesterday!
So, thanks :)

**Comment by polm** [comment]
Ah, thanks for pointing that out! This feature was added in #37.
