### ISSUE TITLE
Typo in Docs: atrrs not an argument of visualize_tokens function(attrs rather) 

### ISSUE THREAD

**Issue by Jcharis** [explosion/spacy-streamlit#4]
Awesome tool @ines . Just a slight typo in the docs for the `visualize_tokens()` function.
In the example  `attrs` is spelt as `atrrs`. We need to make some slight changes.

![Screenshot from 2020-07-09 13-42-50](https://user-images.githubusercontent.com/21055925/87031024-1b6fab80-c1eb-11ea-9d03-2e3de1eab48b.png)
  
Great Work!!. Thanks

**Comment by svlandeg** [comment]
Thanks for the report @Jcharis!

Do you feel like contributing a PR with the fix? The file to be edited is here: https://github.com/explosion/spacy-streamlit/edit/master/README.md
